### ISSUE TITLE
Please add to GxPlugins.lv2 

### ISSUE THREAD

**Issue by magnetophon** [brummer10/GxMatchEQ.lv2#2]
Any reason this is not in there?
Makes thing a lot easier for us packagers!

**Comment by brummer10** [comment]
I usually add plugs to GxPlugins as soon they have a MOD interface. 
This one didn't have that, so . .

**Comment by magnetophon** [comment]
Hmmm,not sure what to think about that.
Should I start packaging this one separately or do you think you'll add it anytime soon?

**Comment by brummer10** [comment]
I didn't think that I'll manage it this year.

**Comment by magnetophon** [comment]
OK, thanks!
