### ISSUE TITLE
Feature request: More bands

### ISSUE THREAD

**Issue by davidhealey** [brummer10/GxMatchEQ.lv2#5]
Can you add more frequency bands to the plugin? Something like 25 or more? Maybe with a menu option to select the number of bands.

Thanks!

**Comment by fps** [comment]
Hi, I just found this: https://github.com/brummer10/MelMatchEQ.lv2 It has 26 bands :))

**Comment by trebmuh** [comment]
@davidhealey this can be closed then.

**Comment by trebmuh** [comment]
:+1:
